import {
  Document, Paragraph, TextRun, HeadingLevel,
  AlignmentType, WidthType, BorderStyle, Packer,
  ShadingType, convertInchesToTwip,
} from "docx";
import type { ProposalExportData } from "./proposal-export";

function heading(text: string, accent: string) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 320, after: 120 },
    border:  { bottom: { style: BorderStyle.SINGLE, size: 4, color: accent.replace("#", "") } },
    children: [new TextRun({ text, bold: true, size: 28, color: accent.replace("#", "") })],
  });
}

function bodyPara(text: string) {
  return new Paragraph({
    spacing: { after: 80 },
    children: [new TextRun({ text, size: 22, color: "374151" })],
  });
}

function divider() {
  return new Paragraph({
    spacing: { before: 80, after: 80 },
    border:  { bottom: { style: BorderStyle.SINGLE, size: 4, color: "e2e8f0" } },
    children: [],
  });
}

export async function generateProposalDOCX(proposal: ProposalExportData): Promise<Buffer> {
  const accent   = (proposal.branding?.brandColor ?? "#1e293b").replace("#", "");
  const orgName  = proposal.branding?.orgName ?? "PryroWriter";
  const formatDate = (d: Date) =>
    new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const children: Paragraph[] = [];

  // ── Cover ──────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing:   { after: 60 },
      children:  [new TextRun({ text: orgName.toUpperCase(), bold: true, size: 20, color: accent, allCaps: true })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing:   { after: 80 },
      children:  [new TextRun({ text: proposal.title, bold: true, size: 44, color: accent })],
    }),
  );

  if (proposal.clientName) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing:   { after: 240 },
        children:  [new TextRun({ text: `Prepared for: ${proposal.clientName}`, size: 22, color: "64748b", italics: true })],
      })
    );
  }

  children.push(divider());

  // ── Meta ───────────────────────────────────────────────────────────────
  const metaLines = [
    `Prepared by: ${proposal.author.name ?? "—"}`,
    `Date: ${formatDate(proposal.createdAt)}`,
    `Version: ${proposal.version}.0`,
    proposal.budget   ? `Budget: ${proposal.budget}`     : "",
    proposal.timeline ? `Timeline: ${proposal.timeline}` : "",
  ].filter(Boolean);

  for (const line of metaLines) {
    children.push(
      new Paragraph({
        spacing: { after: 60 },
        children: [new TextRun({ text: line, size: 20, color: "64748b" })],
      })
    );
  }

  children.push(new Paragraph({ spacing: { before: 200 }, children: [] }));

  // ── Sections ───────────────────────────────────────────────────────────
  const sortedSections = [...proposal.sections].sort((a, b) => a.order - b.order);

  for (const section of sortedSections) {
    children.push(heading(section.title, `#${accent}`));

    for (const line of section.content.split("\n")) {
      children.push(bodyPara(line || " "));
    }

    children.push(new Paragraph({ spacing: { before: 120 }, children: [] }));
  }

  // ── Footer ────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({ spacing: { before: 400 }, children: [] }),
    divider(),
    new Paragraph({
      spacing:   { before: 120 },
      alignment: AlignmentType.CENTER,
      children:  [
        new TextRun({
          text:    `Generated by ${orgName} · PryroWriter · ${formatDate(new Date())}`,
          size:    18,
          color:   "94a3b8",
          italics: true,
        }),
      ],
    })
  );

  const doc = new Document({
    creator:     orgName,
    title:       proposal.title,
    description: proposal.clientName ? `Proposal for ${proposal.clientName}` : proposal.title,
    styles: {
      paragraphStyles: [
        {
          id:      "Normal",
          name:    "Normal",
          run:     { font: "Calibri", size: 22 },
          paragraph: { spacing: { line: 276 } },
        },
        {
          id:      "Heading1",
          name:    "Heading 1",
          basedOn: "Normal",
          next:    "Normal",
          run:     { font: "Calibri", bold: true, size: 28 },
          paragraph: { spacing: { before: 320, after: 120 } },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top:    convertInchesToTwip(1),
              right:  convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left:   convertInchesToTwip(1.2),
            },
          },
        },
        children,
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
