import { formatDate } from "@/lib/utils";

export interface ProposalExportData {
  title:          string;
  clientName:     string | null;
  clientIndustry: string | null;
  proposalType:   string;
  tonePreference: string;
  status:         string;
  version:        number;
  createdAt:      Date;
  updatedAt:      Date;
  budget:         string | null;
  timeline:       string | null;
  author:         { name: string | null };
  sections:       Array<{ key: string; title: string; content: string; order: number }>;
  branding?: {
    orgName:    string;
    logo?:      string | null;
    brandColor: string;
  };
}

function esc(str: string | null | undefined): string {
  if (!str) return "";
  return str
    .replace(/&/g,  "&amp;")
    .replace(/</g,  "&lt;")
    .replace(/>/g,  "&gt;")
    .replace(/"/g,  "&quot;")
    .replace(/'/g,  "&#039;");
}

export function generateProposalHTML(proposal: ProposalExportData, forPDF = false): string {
  const accent = proposal.branding?.brandColor ?? "#1e293b";
  const orgName = proposal.branding?.orgName ?? "PryroWriter";

  const pdfExtras = forPDF ? `
    .header { page-break-after: avoid; }
    h2 { page-break-after: avoid; }
    .section-block { page-break-inside: avoid; }
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
  ` : "";

  const sortedSections = [...proposal.sections].sort((a, b) => a.order - b.order);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>${esc(proposal.title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 860px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.7; font-size: 14px; }

  .header { border-bottom: 4px solid ${accent}; padding-bottom: 24px; margin-bottom: 32px; }
  .header-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; }
  .header h1 { font-size: 28px; margin: 0 0 6px; color: #0f172a; line-height: 1.2; }
  .header .subtitle { color: #64748b; font-size: 14px; margin: 0; }
  .org-badge { background: ${accent}; color: white; padding: 6px 14px; border-radius: 6px; font-size: 12px; font-weight: 600; white-space: nowrap; }

  .meta-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; background: #f8fafc; padding: 16px; border-radius: 8px; margin-bottom: 32px; border: 1px solid #e2e8f0; }
  .meta-item label { display: block; font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #64748b; margin-bottom: 2px; }
  .meta-item p { font-weight: 600; margin: 0; font-size: 13px; color: #1e293b; }

  .section-block { margin-bottom: 36px; }
  .section-title { font-size: 16px; font-weight: 700; color: ${accent}; margin: 0 0 12px; padding-bottom: 8px; border-bottom: 2px solid ${accent}20; }
  .section-content { color: #374151; font-size: 14px; line-height: 1.75; white-space: pre-wrap; }

  hr { border: none; border-top: 1px solid #e2e8f0; margin: 32px 0; }
  .footer { margin-top: 48px; padding-top: 14px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; }
  .footer span { font-size: 11px; color: #94a3b8; }

  @media print { body { padding: 20px; } }
  ${pdfExtras}
</style>
</head>
<body>

<div class="header">
  <div class="header-top">
    <div>
      <h1>${esc(proposal.title)}</h1>
      ${proposal.clientName ? `<p class="subtitle">Prepared for: <strong>${esc(proposal.clientName)}</strong>${proposal.clientIndustry ? ` · ${esc(proposal.clientIndustry)}` : ""}</p>` : ""}
    </div>
    <div class="org-badge">${esc(orgName)}</div>
  </div>
</div>

<div class="meta-grid">
  <div class="meta-item"><label>Prepared by</label><p>${esc(proposal.author.name ?? "—")}</p></div>
  <div class="meta-item"><label>Date</label><p>${formatDate(proposal.createdAt)}</p></div>
  <div class="meta-item"><label>Version</label><p>${proposal.version}.0</p></div>
  ${proposal.budget   ? `<div class="meta-item"><label>Budget</label><p>${esc(proposal.budget)}</p></div>` : ""}
  ${proposal.timeline ? `<div class="meta-item"><label>Timeline</label><p>${esc(proposal.timeline)}</p></div>` : ""}
  <div class="meta-item"><label>Status</label><p>${esc(proposal.status)}</p></div>
</div>

${sortedSections.map((section) => `
<div class="section-block">
  <h2 class="section-title">${esc(section.title)}</h2>
  <div class="section-content">${esc(section.content)}</div>
</div>`).join("\n")}

<hr/>

<div class="footer">
  <span>Generated by ${esc(orgName)} · PryroWriter · ${formatDate(new Date())}</span>
  <span>${esc(proposal.title)} · v${proposal.version}</span>
</div>

</body>
</html>`;
}
